version: 2

sources:
  - name: SNOWFLAKE_SAMPLE_DATA
    description: 'data from snowflake sample data'
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCDS_SF10TCL
    tables:
      - name: STORE_SALES
        description: 'stores sales data'



